### PR TITLE
Fixes #33 unique tool names per Plugin

### LINKED ISSUE #33: RegisterTool throws exception when a duplicate key is registered
PluginAssembly as Prefix

### PR DESCRIPTION
**Pull request by FreeApophis**
* prefix the names internally with the plugin name or GLOBAL

### CODE REVIEW

File: MetaGenerator/ExecutingPluginAssemblyProvider.cs [hunk 1]
```diff
@@ -8,10 +8,12 @@ internal class ExecutingPluginAssemblyProvider : IExecutingPluginAssemblyProvide
     {
         private Assembly? _pluginAssembly;
 
+        public bool HasPluginContext => _pluginAssembly != null;
```
Comment (tautropfli) [inline MetaGenerator/ExecutingPluginAssemblyProvider.cs]:
```suggestion
        public bool HasPluginContext => _pluginAssembly is { };
```

**Review by tautropfli — CHANGES_REQUESTED** [review]

File: MetaGenerator/ExecutingPluginAssemblyProvider.cs (hunk 1 above)
Comment (FreeApophis) [reply MetaGenerator/ExecutingPluginAssemblyProvider.cs]: indeed
